import "./globals.css";

export const Metadata = {
  title: "My Todo-List",
  description: "Generated by Sekou S Seh",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">{children}</body>
    </html>
  );
}
